server:
  port: 8080
spring:
  application:
    name: distributor-network
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
