server:
  port: 8081

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
distributor:
  host: localhost
  port: 8080